[workspace]
resolver = "2"
members = ["core/*"]

[workspace.package]
version = "2.0.0"
edition = "2021"
license = "Apache-2.0"
homepage = "https://ore.supply"
documentation = "https://ore.supply"
repository = "https://github.com/regolith-labs/ore"
readme = "./README.md"
keywords = ["solana", "crypto", "mining"]

[workspace.dependencies]
drillx = { git = "https://github.com/regolith-labs/drillx", branch = "master", features = ["solana"] }
mpl-token-metadata = "4.1.2"
solana-program = "1.18"
spl-token = { version = "^4", features = ["no-entrypoint"] }
spl-associated-token-account = { version = "^2.2", features = [ "no-entrypoint" ] } 
